# ----------------------------------------------------------------------------#
#                                                                             #
#                           Cookie Clicker config                             #
#                                                                             #
#                                  by Nikl                                    #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "default"

rules:
  # enable/disable sound
  playSounds: true

# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

# Option to save your game in a regular interval while inside the GUI
autoSave:
  enabled: true
  # saving interval in seconds
  interval: 300

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "cookie"
    # display name of the button
    displayName: "&3Cookie Clicker"
    # lore of the button
    lore:
      - ""
      - "&1Conquer the world with your cookies."
      - ""
      - "&5&o\"Come to the dark side of the force..."
      - "&5&o    We have cookies!\""
  gameButtons:
    weekly:
      materialData: "cookie"
      displayName: "&aCookie Clicker"
      lore:
        - ""
        - "&6Click on the cookie!"
        - ""
        - "&5&o\"Yes..."
        - "  &5&oIt's that simple.\""
      slot: 20
      cost: 0
      # if true the best score of this button is saved
      saveStats: true
      # 3 minutes idle time (afterwards the game is paused)
      idleSeconds: 180

      # after the set amount of clicks on the cookie it's position will change
      #   This is optional and can be turned off by setting it to 0 or a negative number
      #   This option is supposed to prevent players from using autoclickers
      moveCookieAfterClicks: 100
      # all keys have to be integers otherwise they will be ignored and a warning will be printed in the console

      # money is only paid if economy is enabled
      # tokens can be used in the GameBox shop

      # You can add as many intervals as you want to. The order of the intervals doesn't matter
      #   the given rewards will always be used if the game is finished with a score between the key and the
      #   next higher key. For the highest key the interval goes to infinity
      scoreIntervals:
        0:
          money: 0
          tokens: 0
        250:
          money: 10
          token: 1
        1000:
          money: 100
          tokens: 1
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    weekly:
      materialData: "PLAYER_HEAD"
      displayName: "&6Cookie Clicker &c&lTop list"
      slot: 24
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '     &6Cookie Clicker &rTop List'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %score% for the highest score of the player
      skullLore:
        - ''
        - '&6Rank:&1 %rank%'
        - '&6Cookies:&1 %score%'

# Global boosts that give multipliers for clicking and producing cookies
globalBoosts:
  # Activation switch for the boost system
  active: false
  # For the scheduling of global boosts the plugin CalendarEvents is required!
  #    FYI: boosts can overlap and will stack. They are rounded to the first decimal place.
  boosts:
    # every Sunday, boost the first 10 minutes of a full hour (for more examples of Calendar events visit: https://www.nikl.me/projects/calendarevents/)
    example1:
      timing:
        occasion: "Sunday"
        time: "xx:00"
      # duration of the boost in minutes (required and > 0)
      duration: 10
      # multiplier for cookies per click
      clickingBoost: 3
      # multiplier for cookies produced per second
      productionBoost: 2
    # larger boosts on Christmas
    example2:
      timing:
        occasion: "24.12"
        time: "xx:00"
      # duration of the boost (in minutes!)
      duration: 15
      clickingBoost: 4
      productionBoost: 4
